name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v2
      - name: Build Client
        run: cargo build --release --bin neutun --verbose
      - name: Compress
        run: tar -czvf neutun-${{ matrix.os }}.tar.gz target/release/neutun
      - name: Upload Client Binary
        uses: actions/upload-artifact@v1
        with:
          name: neutun-${{ matrix.os }}
          path: target/release/neutun

  build_win:
    runs-on: windows-latest
    steps:
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v2
      - name: Build Client
        run: cargo build --release --bin neutun --verbose
      - name: Upload Client Binary
        uses: actions/upload-artifact@v1
        with:
          name: neutun-windows-latest.exe
          path: target/release/neutun.exe

  publish:
    needs: [build, build_win]
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}    
        
      - name: Download macOS
        uses: actions/download-artifact@v1
        with:
          name: neutun-macOS-latest
          path: macOS/neutun/${{ steps.get_version.outputs.VERSION }}/bin/

      - name: Download ubuntu
        uses: actions/download-artifact@v1
        with:
          name: neutun-ubuntu-latest
          path: linux/

      - name: Download windows
        uses: actions/download-artifact@v1
        with:
          name: neutun-windows-latest.exe
          path: windows/

      - name: Compress
        run: |
          chmod +x macOS/neutun/${{ steps.get_version.outputs.VERSION }}/bin/neutun
          chmod +x linux/neutun
          export TAG="${{ steps.get_version.outputs.VERSION }}"
          cp windows/neutun.exe neutun-windows.exe
          tar -C macOS/ -czvf "neutun-$TAG.catalina.bottle.tar.gz" neutun/${{ steps.get_version.outputs.VERSION }}/bin/neutun
          cp "neutun-$TAG.catalina.bottle.tar.gz" "neutun-$TAG.big_sur.bottle.tar.gz"
          tar -C linux/ -czvf neutun-linux.tar.gz neutun

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "neutun-${{ steps.get_version.outputs.VERSION }}.big_sur.bottle.tar.gz,neutun-${{ steps.get_version.outputs.VERSION }}.catalina.bottle.tar.gz,neutun-linux.tar.gz,neutun-windows.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
